name: 
channels:
  - conda-forge
  - pkgs/main
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.11=h22baa00_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py312h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
    - Markdown==3.9
    - PyJWT==2.10.1
    - Send2Trash==1.8.3
    - Werkzeug==3.1.3
    - absl-py==2.3.1
    - annotated-doc==0.0.3
    - annotated-types==0.7.0
    - argon2-cffi==25.1.0
    - argon2-cffi-bindings==25.1.0
    - arrow==1.4.0
    - asttokens==3.0.0
    - async-lru==2.0.5
    - babel==2.17.0
    - backoff==2.2.1
    - beautifulsoup4==4.14.2
    - bleach==6.3.0
    - boto3==1.40.63
    - botocore==1.40.63
    - cachetools==6.2.1
    - cffi==2.0.0
    - click==8.3.0
    - comm==0.2.3
    - contourpy==1.3.3
    - cycler==0.12.1
    - debugpy==1.8.17
    - decorator==5.2.1
    - defusedxml==0.7.1
    - docker==7.1.0
    - executing==2.2.1
    - fastapi==0.120.3
    - fastjsonschema==2.21.2
    - fonttools==4.60.1
    - fqdn==1.5.1
    - google-auth==2.41.1
    - google-auth-oauthlib==1.2.3
    - grpcio==1.76.0
    - httptools==0.7.1
    - iniconfig==2.3.0
    - ipykernel==6.26.0
    - ipython==8.17.2
    - ipywidgets==8.1.1
    - isoduration==20.11.0
    - jedi==0.19.2
    - jmespath==1.0.1
    - json5==0.12.1
    - jsonpointer==3.0.0
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - jupyter-events==0.12.0
    - jupyter-lsp==2.3.0
    - jupyter_client==8.6.3
    - jupyter_core==5.9.1
    - jupyter_server==2.17.0
    - jupyter_server_terminals==0.5.3
    - jupyterlab==4.2.0
    - jupyterlab_pygments==0.3.0
    - jupyterlab_server==2.28.0
    - jupyterlab_widgets==3.0.15
    - kiwisolver==1.4.9
    - lark==1.3.1
    - lightning==2.5.5
    - lightning-cloud==0.5.70
    - lightning-utilities==0.15.2
    - lightning_sdk==2025.10.31
    - litai==0.0.10
    - litdata==0.2.58
    - litserve==0.2.16
    - matplotlib==3.8.2
    - matplotlib-inline==0.2.1
    - mistune==3.1.4
    - nbclient==0.10.2
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - notebook_shim==0.2.4
    - oauthlib==3.3.1
    - obstore==0.8.2
    - pandocfilters==1.5.1
    - parso==0.8.5
    - pexpect==4.9.0
    - pip==25.3
    - platformdirs==4.5.0
    - pluggy==1.6.0
    - prometheus_client==0.23.1
    - prompt_toolkit==3.0.52
    - ptyprocess==0.7.0
    - pure_eval==0.2.3
    - pyasn1==0.6.1
    - pyasn1_modules==0.4.2
    - pycparser==2.23
    - pydantic==2.12.3
    - pydantic_core==2.41.4
    - pyparsing==3.2.5
    - pytest==9.0.0
    - python-dotenv==1.2.1
    - python-json-logger==4.0.0
    - python-multipart==0.0.20
    - pytorch-lightning==2.5.5
    - pyzmq==27.1.0
    - referencing==0.37.0
    - requests-oauthlib==2.0.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rfc3987-syntax==1.1.0
    - rpds-py==0.28.0
    - rsa==4.9.1
    - s3transfer==0.14.0
    - simple-term-menu==1.6.6
    - soupsieve==2.8
    - stack-data==0.6.3
    - starlette==0.49.1
    - tensorboard==2.15.1
    - tensorboard-data-server==0.7.2
    - terminado==0.18.1
    - tifffile==2025.10.16
    - tinycss2==1.4.0
    - torchmetrics==1.7.4
    - tornado==6.5.2
    - traitlets==5.14.3
    - triton_kernels==1.0.0
    - typing-inspection==0.4.2
    - uri-template==1.3.0
    - uv==0.9.8
    - uvicorn==0.38.0
    - uvloop==0.22.1
    - watchfiles==1.1.1
    - wcwidth==0.2.14
    - webcolors==25.10.0
    - webencodings==0.5.1
    - websocket-client==1.9.0
    - websockets==15.0.1
    - wget==3.2
    - widgetsnbextension==4.0.14

prefix: "/system/conda/miniconda3/envs/cloudspace"
